<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="stylesheet.css" type="text/css" rel="stylesheet" />
    <title>Galerie | Ferienwohnung Baerl</title>
</head>
<body id="galerie">
<header>
    <div class="headercontainer">
        <ul class="headerliste">
            <li id="navi01">
                <span>
                    <a href="index.phtml">Home</a>
                </span>
            </li>
            <li id="navi02">
                <span>
                    <a href="galerie.phtml">Galerie</a>
                </span>
            </li>
            <li id="navi03">
                <span>
                    <a href="preise.phtml">Preise</a>
                </span>
            </li>
            <li id="navi04">
                <span>
                    <a href="kontakt.phtml">Kontakt</a>
                </span>
            </li>
        </ul>
<!--        <div class="ueberschrift">-->
<!--            <p class="ueberschrift">-->
<!--                <a href="index.phtml">Ferienwohnung Baerl</a>-->
<!--            </p>-->
<!--        </div>-->
    </div>
</header>
<div>
    <h2 class="topic">Fotogalerie Ferienwohnung</h2>
</div>
<div class="bildergalerie">
    <div class="galeriebox">
        <img src="images/galerie1.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie2.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie3.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie4.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie5.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie6.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie7.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie10.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie9.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie8.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie11.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie12.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie13.jpg" class="galeriebild">
    </div>
    <div class="galeriebox">
        <img src="images/galerie14.jpg" class="galeriebild">
    </div>
</div>
<footer>
    <div class="footercontainer">
        <a href="index.phtml">Impressum</a>
        <a href="datenschutz.html">Datenschutz</a>
    </div>
</footer>