<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="stylesheet.css" type="text/css" rel="stylesheet" />
    <title>Home | Ferienwohnung Baerl</title>
</head>
<body id="index">
<header>
    <div class="headercontainer">
        <ul class="headerliste">
            <li id="navi01">
                <span>
                    <a href="index.phtml">Home</a>
                </span>
            </li>
            <li id="navi02">
                <span>
                    <a href="galerie.phtml">Galerie</a>
                </span>
            </li>
            <li id="navi03">
                <span>
                    <a href="preise.phtml">Preise</a>
                </span>
            </li>
            <li id="navi04">
                <span>
                    <a href="kontakt.phtml">Kontakt</a>
                </span>
            </li>
        </ul>
<!--        <div class="ueberschrift">-->
<!--            <p class="ueberschrift">-->
<!--                <a href="index.phtml">Ferienwohnung Baerl</a>-->
<!--            </p>-->
<!--        </div>-->
    </div>
</header>
<div class="hometopic">
    <h2 class="topic">Ferienwohnung in Duisburg-Baerl am linken Niederrhein</h2>
</div>
<div class="grey">
    <div class="introcontainer">
        <div class="introitem">
            <div class="introbox">
                <img src="images/test.jpg" alt="Küche" class="introbild">
            </div>
            <div class="introbox">
                <h2>Ausstattung</h2>
                <ul class="introliste">
                    <li>
                        Modern eingerichtete Ferienwohnung in Duisburg-Baerl
                    </li>
                    <li>
                        offener Grundriss ca. 40qm
                    </li>
                    <li>
                        Wohn-/Schlafraum (Boxspringbett 180x200)
                    </li>
                    <li>
                        Küche mit Essbereich
                    </li>
                    <li>
                        Bad mit Dusche/WC
                    </li>
                    <li>
                        Erdgeschoss mit seperatem Eingang
                    </li>
                    <li>
                        Einstellmöglichkeit für Fahrräder
                    </li>
                    <li>
                        WLAN
                    </li>
                    <li>
                        TV
                    </li>
                    <li>
                        öffentliche Parkmöglichkeiten vor dem Haus
                    </li>
                    <li>
                        Nichtraucherwohnung
                    </li>
                    <li>
                        Spülmaschine
                    </li>
                    <li>
                        Herd
                    </li>
                    <li>
                        Kühlschrank
                    </li>
                    <li>
                        Kaffemaschine
                    </li>
                    <li>
                        Wasserkocher
                    </li>
                </ul>
            </div>
        </div>
        <div class="introitem">
            <div class="introbox">
                <img src="images/test2.jpg" alt="Rhein" class="introbild">
            </div>
            <div class="introbox">
                <h2>Umgebung</h2>
                <ul class="introliste">
                    <li>
                        Duisburg-Baerl am Rhein
                    </li>
                    <li>
                        Sehr gute Autobahnanbindung A40/A57/A42
                    </li>
                    <li>
                        Duisburg-Zentrum ca. 14km
                    </li>
                    <li>
                        Düsseldorf-Zentrum ca. 40km
                    </li>
                    <li>
                        Centro Oberhausen ca. 20km
                    </li>
                    <li>
                        Moers-Zentrum ca. 7km
                    </li>
                    <li>
                        Idealer Ausgangspunkt für Radtouren am Niederrhein <br>oder die Route der Industriekultur im Ruhrgebiet
                    </li>
                    <li>
                        Der Loheidersee lädt zu entspannten Spaziergängen ein (ca. 1,5km)
                    </li>
                    <li>
                        Einkaufsmöglichkeiten in der Nähe
                        <ul>
                            <li>
                                Supermarkt (850m)
                            </li>
                            <li>
                                2 Bäckereien (50m, 150m)
                            </li>
                            <li>
                                Verschiedene Restaurants in näherer Umgebung
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="brightgrey">
    <div class="balkencontainer">
        <div class="smallpic">
            <img src="images/standort.jpg">
        </div>
        <div class="text">
            <h2>Standort</h2>
        </div>
    </div>
</div>
<div class="white">
    <div class="balkencontainer">
        <div class="text">
            <div class="description">
                <h2>
                    Fotogalerie Ferienwohnung
                </h2>
                <p>
                    Sie sind neugierig auf unser Appartement?
                </p>
                <p>
                    Dann schauen Sie sich unsere Galerie an und machen Sie sich ein Bild!
                </p>
            </div>
            <div class="buttonline">
                <a class="linkbutton" href="galerie.phtml">
                    Galerie
                </a>
            </div>
        </div>
        <div class="smallpic">
            <img src="images/home%204.jpg">
        </div>
    </div>
</div>
<div class="brightgrey">
    <div class="balkencontainer">
        <div class="smallpic">
            <img src="images/home5.jpg">
        </div>
        <div class="text">
            <div>
                <h2>
                    Preise
                </h2>
            </div>
            <div class="buttonline">
                <a class="linkbutton" href="preise.phtml">
                    Preisliste
                </a>
            </div>
        </div>
    </div>
</div>
<footer>
    <div class="footercontainer">
        <a href="index.phtml">Impressum</a>
        <a href="datenschutz.html">Datenschutz</a>
    </div>
</footer>