<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="stylesheet.css" type="text/css" rel="stylesheet" />
    <title>Preise | Ferienwohnung Baerl</title>
</head>
<body id="preise">
<header>
    <div class="headercontainer">
        <ul class="headerliste">
            <li id="navi01">
                <span>
                    <a href="index.phtml">Home</a>
                </span>
            </li>
            <li id="navi02">
                <span>
                    <a href="galerie.phtml">Galerie</a>
                </span>
            </li>
            <li id="navi03">
                <span>
                    <a href="preise.phtml">Preise</a>
                </span>
            </li>
            <li id="navi04">
                <span>
                    <a href="kontakt.phtml">Kontakt</a>
                </span>
            </li>
        </ul>
<!--        <div class="ueberschrift">-->
<!--            <p class="ueberschrift">-->
<!--                <a href="index.phtml">Ferienwohnung Baerl</a>-->
<!--            </p>-->
<!--        </div>-->
    </div>
</header>
<div>
    <h2 class="topic">Preise</h2>
</div>
<div class="preisgerüst">
    <div class="preiscontainertop">
        <div class="preistext">
            <div class="textbloecke">
                <p>
                    1 Pers. 1-2 Nächte - 65€ pro Nacht
                </p>
                <p>
                    2 Pers. 1-2 Nächte - 75€ pro Nacht
                </p>
            </div>
            <div class="textbloecke">
                <p>
                    1 Pers. bis 7 Nächte - 60€ pro Nacht
                </p>
                <p>
                    2 Pers. bis 7 Nächte - 70€ pro Nacht
                </p>
            </div>
            <div class="textbloecke">
                <p>
                    1 Pers. bis 14 Nächte - 55€ pro Nacht
                </p>
                <p>
                    2 Pers. bis 14 Nächte - 65 pro Nacht
                </p>
            </div>
            <div  class="inklusive">
                <p>
                    inkl. Bettwäsche und Handtücher
                </p>
            </div>
        </div>
        <div class="preisbox">
            <img src="images/galerie7.jpg" class="preisbild">
        </div>
    </div>
    <div class="preiscontainermid">
        <div class="aufenthalttext">
            <h2>Längere Aufenthalte</h2>
            <p>
                Nach Absprache
            </p>
        </div>
        <div class="preisbox">
            <img src="images/galerie6.jpg" class="preisbild">
        </div>
    </div>
</div>

<footer>
    <div class="footercontainer">
        <a href="index.phtml">Impressum</a>
        <a href="datenschutz.html">Datenschutz</a>
    </div>
</footer>