<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="../style/stylesheet.css" type="text/css" rel="stylesheet" />
    <title>Home | Ferienwohnung Baerl</title>
</head>
<body id="impressum">
<header>
    <div class="headercontainer">
        <ul class="headerliste">
            <li id="navi01">
                <span>
                    <a href="../index.phtml">Home</a>
                </span>
            </li>
            <li id="navi02">
                <span>
                    <a href="galerie.phtml">Galerie</a>
                </span>
            </li>
            <li id="navi03">
                <span>
                    <a href="preise.phtml">Preise</a>
                </span>
            </li>
            <li id="navi04">
                <span>
                    <a href="kontakt.phtml">Kontakt</a>
                </span>
            </li>
        </ul>
        <!--        <div class="ueberschrift">-->
        <!--            <p class="ueberschrift">-->
        <!--                <a href="index.phtml">Ferienwohnung Baerl</a>-->
        <!--            </p>-->
        <!--        </div>-->
    </div>
</header>
<div class="impressumcontainer">
    <div class="impressumsbox">
        <h1>Impressum</h1>
        <p>Ingrid und Gerd Pousen</p>
        <p>Geststr. 4</p>
        <p>47199 Duisburg</p>
    </div>
</div>
<footer>
    <div class="footercontainer">
        <a href="../index.phtml">Impressum</a>
        <a href="datenschutz.html">Datenschutz</a>
    </div>
</footer>